directory: ~/Music

plugins: info convert fetchart embedart missing

convert:
  max_bitrate: 320
  never_convert_lossy_files: yes

fetchart:
  minWidth: 500
  maxWidth: 1024
  enforce_ratio: yes

embedart:
  maxwidth: 1024
  remove_art_file: yes
